<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQosorb3\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQosorb3/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerQosorb3.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerQosorb3\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerQosorb3\appDevDebugProjectContainer([
    'container.build_hash' => 'Qosorb3',
    'container.build_id' => 'da4fd49c',
    'container.build_time' => 1614267878,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQosorb3');
